from inference_model.inference_model_interface import InferenceModelInterface
from inference_model.inference_model_detectron2 import InferenceModelDetectron2
from inference_model.inference_model_test import InferenceModelTest
